LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := libgcam
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE).so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libgcam_swig_jni
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE).so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#LOCAL_MODULE := libjni_jpegutil
#LOCAL_SRC_FILES := lib/$(LOCAL_MODULE).so
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_SUFFIX := .so
#LOCAL_MODULE_CLASS := SHARED_LIBRARIES
#include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#LOCAL_MODULE := libjni_tinyplanet
#LOCAL_SRC_FILES := lib/$(LOCAL_MODULE).so
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_SUFFIX := .so
#LOCAL_MODULE_CLASS := SHARED_LIBRARIES
#include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#LOCAL_MODULE := libjpeg
#LOCAL_SRC_FILES := lib/$(LOCAL_MODULE).so
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_SUFFIX := .so
#LOCAL_MODULE_CLASS := SHARED_LIBRARIES
#include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := liblightcycle
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE).so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#LOCAL_MODULE := libnativehelper_compat_libc++
#LOCAL_SRC_FILES := lib/$(LOCAL_MODULE).so
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_SUFFIX := .so
#LOCAL_MODULE_CLASS := SHARED_LIBRARIES
#include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := librefocus
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE).so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := librs.layered_filter_fast_f32
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE).so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#LOCAL_MODULE := librsjni
#LOCAL_SRC_FILES := lib/$(LOCAL_MODULE).so
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_SUFFIX := .so
#LOCAL_MODULE_CLASS := SHARED_LIBRARIES
#include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#LOCAL_MODULE := libRSSupport
#LOCAL_SRC_FILES := lib/$(LOCAL_MODULE).so
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_SUFFIX := .so
#LOCAL_MODULE_CLASS := SHARED_LIBRARIES
#include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := GCamera2
LOCAL_MODULE_OWNER := Google
LOCAL_SRC_FILES := $(LOCAL_MODULE).apk
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .apk
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_JNI_SHARED_LIBRARIES := libgcam libgcam_swig_jni libjni_jpegutil libjni_tinyplanet libjpeg liblightcycle libnativehelper_compat_libc++ librefocus librsjni libRSSupport librs.layered_filter_fast_f32
LOCAL_OVERRIDES_PACKAGES := Camera2
include $(BUILD_PREBUILT)
